- name: setup service account for updates
  hosts: localhost
  connection: local
  become: true
  vars:
    del_user: ['netherkids_external_user', 'external']
  handlers:
    - name: restart_sshd
      service:
        name: sshd
        state: restarted
  tasks:
    - name: Add the Update service user 
      ansible.builtin.user:
        name: svcusr_update
        uid: 1122
        groups: sudo
        shell: /bin/bash
        password: $6$gbKVwLMz$yM3W1Qbe.WJcLVnt.KntrXgHKPNSQQqhvngV2XQ3Fp3DPcWSk4QWP.7DjFFYEMjspbU0oJFkrdXNmcfe63HHA1
        createhome: yes 
        home: /home/.svcusr_update
        
    - name: Get all Users
      shell: 'cut -d: -f1 /etc/passwd'
      register: all_users
    - name: Remove Users
      ansible.builtin.user:
        name: "{{ item }}"
        state: absent
        remove: true
      with_items: "{{ del_user }}"
      when: item in all_users.stdout_lines

    - name: Set authorized keys taken from url
      ansible.posix.authorized_key:
        user: svcusr_update
        state: present
        key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINCYQhiiuXHwlbQi8eD05wvTbAx1KZP4f0VGaQ6Ue60h update@ansible
    - name: Update SSH settings
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}" 
      loop:
        - regexp: ^[#\s]*Port
          line: Port 710
        - regexp: ^[#\s]*PermitRootLogin
          line: PermitRootLogin no
        - regexp: ^[#\s]*PasswordAuthentication
          line: PasswordAuthentication no
        - regexp: ^[#\s]*PermitEmptyPasswords
          line: PermitEmptyPasswords no
        - regexp: ^[#\s]*KbdInteractiveAuthentication
          line: KbdInteractiveAuthentication no
        - regexp: ^[#\s]*ChallengeResponseAuthentication
          line: ChallengeResponseAuthentication no
        - regexp: ^[#\s]*MaxAuthTries
          line: MaxAuthTries 7
        - regexp: ^[#\s]*AllowTcpForwarding
          line: AllowTcpForwarding no
        - regexp: ^[#\s]*X11Forwarding
          line: X11Forwarding no
        - regexp: ^[#\s]*AllowAgentForwarding
          line: AllowAgentForwarding no
        - regexp: ^[#\s]*AuthorizedKeysFile
          line: AuthorizedKeysFile .ssh/authorized_keys
        - regexp: ^[#\s]*RSAAuthentication
          line: "#RSAAuthentication yes"
        - regexp: ^[#\s]*DenyUsers
          line: DenyUsers root
        - regexp: ^[#\s]*DenyGroups
          line: DenyGroups root
        - regexp: ^[#\s]*AllowUsers
          line: AllowGroups sudo
      notify:
         - restart_sshd
