- name: setup service account for updates
  hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
    - name: Add the Update service user 
      ansible.builtin.user:
        name: svcusr_update
        uid: 1122
        groups: sudo
        shell: /bin/bash
        password: $6$gbKVwLMz$yM3W1Qbe.WJcLVnt.KntrXgHKPNSQQqhvngV2XQ3Fp3DPcWSk4QWP.7DjFFYEMjspbU0oJFkrdXNmcfe63HHA1
        createhome: yes 
        home: /home/.svcusr_update

    - name: Set authorized keys taken from url
      ansible.posix.authorized_key:
        user: svcusr_update
        state: present
        key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINCYQhiiuXHwlbQi8eD05wvTbAx1KZP4f0VGaQ6Ue60h update@ansible
    - name: Update SSH settings
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}" 
      loop:
        - regexp: ^\(#\|\)Port
          line: Port 710
        - regexp: ^\(#\|\)PermitRootLogin
          line: PermitRootLogin no
        - regexp: ^\(#\|\)PasswordAuthentication
          line: PasswordAuthentication no
        - regexp: ^\(#\|\)PermitEmptyPasswords
          line: PermitEmptyPasswords no
        - regexp: ^\(#\|\)KbdInteractiveAuthentication
          line: KbdInteractiveAuthentication no
        - regexp: ^\(#\|\)ChallengeResponseAuthentication
          line: ChallengeResponseAuthentication no
        - regexp: ^\(#\|\)MaxAuthTries
          line: MaxAuthTries 7
        - regexp: ^\(#\|\)AllowTcpForwarding
          line: AllowTcpForwarding no
        - regexp: ^\(#\|\)X11Forwarding
          line: X11Forwarding no
        - regexp: ^\(#\|\)AllowAgentForwarding
          line: AllowAgentForwarding no
        - regexp: ^\(#\|\)AuthorizedKeysFile
          line: AuthorizedKeysFile .ssh\/authorized_keys/
